### ISSUE TITLE
Allow for custom modules in /bin/somos

### ISSUE THREAD

**Issue by mvriel** [somos/framework#17]
The auto-wiring of PHP-DI allows us to remove the need to have Service Definitions for all services that need to be instantiated. However: sometimes it is necessary to help PHP-DI by adding a definition to declare which concrete implementation an interface uses or to construct an object of a specific class using a factory.

In order to enable this it must be possible to load additional service definitions for PHP-DI, this can also introduce settings, such as the host name for Doctrine.

Requirements:

- [x] It must be possible to load additional DI definitions in `Somos::start()`
- [x] When calling ./vendor/bin/somos all modules selected by the user need to be loaded
- [x] The above must be as intuitive as possible and preferably not introduce any required files or anything similar

**Comment by mvriel** [comment]
Traditionally the Cli Controller and FrontController have been separated in many frameworks. They use the same kernel instantiation but after that you need another two files (one for each environment) to have both command line tools and a front controller to handle the web requests.

With Somos I introduce the concept of 'scopes'. Messages can be restricted to run in a scope, or combination thereof, so that we can say: all command line utilities only run from the CLI but all web tools run from the webserver. This allows us to use the same file for kernel instantation, web request handling and command line handling.

Should a user wish to make that separation than they can do so; it is expected it will save a small amount of performance so in a high-performance environment it may matter.

**Comment by mvriel** [comment]
@mnapoli I thought you might be interested in this?

**Comment by mnapoli** [comment]
:+1:
